image: archlinux
triggers:
  - action: email
    condition: failure
    to: Dmitriy Morozov <dmitriy@mrzv.org>
packages:
  - cmake
  - openmpi
  - jq
sources:
  - https://github.com/diatomic/diy
secrets:
  - d5741a21-e00a-4cf7-9a75-262c33d3ecd0
environment:
  OMPI_MCA_rmaps_base_oversubscribe: 1
tasks:
  #- configure: |
  #    mkdir diy/build
  #    cd diy/build
  #    cmake ..
  #- build: |
  #    cd diy/build
  #    make
  #- test: |
  #    cd diy/build
  #    make test
  - dependents: |
      cd diy
      sh conf/ci/builds.sr.ht/launch-dependents.sh

